post_install() {
	set -e
	allusers=/usr/share/lightworks

	echo $((`cat /dev/urandom|od -N1 -An -i` % 2500)) > /usr/share/lightworks/machine.num

	chmod a+rw /usr/share/lightworks/Preferences
	chmod a+rw "/usr/share/lightworks/Audio Mixes"

  	update-desktop-database -q
  	gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

post_upgrade() {
  post_install $1
}

post_remove() {
  post_install $1
}
